In [1]:
# Install and import TF2
!pip install -q tensorflow==2.0.0
import tensorflow as tf
print(tf.__version__)

     |████████████████████████████████| 86.3MB 40kB/s 
     |████████████████████████████████| 450kB 42.8MB/s 
     |████████████████████████████████| 3.8MB 47.3MB/s 
     |████████████████████████████████| 81kB 10.3MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.8.2 which is incompatible.
2.0.0


In [0]:
# Additional imports
from tensorflow.keras.layers import Input,Dense,Flatten,SimpleRNN
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD,Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
# Things we should know and memorize

# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units (neurons)
# K = number of output units (neurons)

In [0]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [0]:
# Make an RNN

M = 5 # number of hidden units

i = Input(shape=(T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i,x)

In [7]:
# Get the output
Yhat = model.predict(X)
print(Yhat)
print('Yhat.shape', Yhat.shape)

[[-0.614428  0.251425]]
Yhat.shape (1, 2)


In [8]:
# see if we can replicate this output
# get the weights first
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [9]:
# see what's returned
model.layers[1].get_weights()

[array([[-0.31999815, -0.2864352 ,  0.85991806,  0.6280498 , -0.14360756],
        [-0.7197159 , -0.6320561 , -0.342704  , -0.26901972, -0.53086317],
        [-0.78973997, -0.24185795,  0.6893701 ,  0.8440679 , -0.51694995]],
       dtype=float32),
 array([[ 0.6609564 ,  0.28463316, -0.56149614, -0.31115374,  0.26462454],
        [-0.19235975, -0.23447323,  0.28700507, -0.49051946,  0.7648784 ],
        [-0.0645247 , -0.59844065, -0.27742928, -0.5832584 , -0.46962535],
        [ 0.72244316, -0.38197118,  0.56100094,  0.10725141, -0.07712894],
        [-0.00684184, -0.59997755, -0.45897838,  0.55756694,  0.34414846]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [10]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a,b,c = model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [0]:
Wx,Wh,bh = model.layers[1].get_weights()
Wo,bo = model.layers[2].get_weights() # output layer

In [12]:
# we manualy calculate the output
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx)+h_last.dot(Wh)+bh)
  y = h.dot(Wo)+bo # we only care about this value on the last iteration
  Yhats.append(y)
  #important: assign h to h_last
  h_last = h

#print the final output and confirm
print(Yhats[-1])

[-0.61442795  0.25142496]


In [0]:
# Calculate for multiple outputs N>1